name: test-lookup-only

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-save:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate files in working directory
        shell: bash
        run: src/create-cache-files.sh ${{ runner.os }} test-cache
      - name: Generate files outside working directory
        shell: bash
        run: src/create-cache-files.sh ${{ runner.os }} ~/test-cache
      - name: Save cache
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_REGION: "us-east-1"
        with:
          endpoint: ${{ secrets.ENDPOINT }}
          bucket: ${{ secrets.BUCKET }}
          use-fallback: false
          key: test-${{ runner.os }}-${{ github.run_id }}
          path: |
            test-cache
            ~/test-cache

  test-lookup-only:
    needs: test-save
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lookup cache
        id: lookup
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          # AWS_SESSION_TOKEN: "xxx"
          AWS_REGION: "us-east-1"
        with:
          endpoint: ${{ secrets.ENDPOINT }}
          bucket: ${{ secrets.BUCKET }}
          key: test-${{ runner.os }}-${{ github.run_id }}
          lookup-only: true
          path: |
            test-cache
            ~/test-cache
      - name: verify cache hit
        env:
          CACHE_HIT: ${{ steps.lookup.outputs.cache-hit }}
          CACHE_SIZE: ${{ steps.lookup.outputs.cache-size }}
        shell: bash
        run: |
          echo "CACHE_HIT $CACHE_HIT"
          echo "CACHE_SIZE $CACHE_SIZE"
          ls -R ~/test-cache || true
          ls -R test-cache || true
          src/create-cache-files.sh ${{ runner.os }} test-cache check_not_exist
